In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
x = torch.rand(5,3)
print(x)

tensor([[0.8694, 0.9260, 0.7253],
        [0.3670, 0.7685, 0.5288],
        [0.7830, 0.8297, 0.3427],
        [0.1996, 0.6814, 0.5878],
        [0.3216, 0.3919, 0.0167]])


In [6]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_ones = torch.ones_like(x_data)
print(f"ONes tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype= torch.float)
print(f"Random tensor: \n {x_rand} \n")
      
      

ONes tensor: 
 tensor([[1, 1],
        [1, 1]])

Random tensor: 
 tensor([[0.3384, 0.9734],
        [0.4379, 0.1515]]) 



# Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
# Matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

# Random Torch 

In [9]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3288, 0.0576, 0.8525, 0.2575],
        [0.4688, 0.7154, 0.5540, 0.2309],
        [0.7073, 0.0578, 0.6760, 0.4061]])

In [10]:
#create a random tensor with similar shape to a image tensor
# 3 -> color channel
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [11]:
# zeros and ones

In [12]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### create a range of tensors and tensors-like

In [20]:
one_to_ten =  torch.arange(start = 0,end = 20,step = 3)

In [21]:
torch.zeros_like(input =  one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

**Notes-**-Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning
1. Tensor not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                               device = None, 
                               requires_grad = False)# weather of not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)