In [2]:
import torch
#nn contains all of pytorch's building blocks for neural networks
from torch import nn
import matplotlib.pyplot as plt

torch.__version__

'2.2.0+cpu'

In [4]:
# y = a + bX
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02
#capital represents matrix
X = torch.arange(start,end,step).unsqueeze(dim = 1)
#small letter represents vector
y =  weight*X + bias

X[:10],y[:10], len(X), len(y)


(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]),
 50,
 50)

In [8]:
## splitting data into training and test sets

train_split = int(0.8 * len(X))
X_train,y_train = X[:train_split],y[:train_split]
X_test, y_test = X[train_split:],y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [9]:
#visualize
def plot_predictions(train_data = X_train,
                    train_labels = y_train,
                    test_data = X_test,
                    test_labels=y_test,
                    predictions = None):
    plt.figure(figsize = (10,7))
    
    plt.scatter(train_data, train_labels,c = "b", s = 4, label="Training data")
    
    plt.scatter(test_data, test_labels,c = "r", s = 5, label="Testing data")
    
    
    if predictions is not None:
        plt.scatter(test_data, predictions, c="r", s= 4, label ='Predictions')
        
    plt.legend(prop={"size",14});
    

In [13]:
# Build model

#first Pytorch model!

#Create linear regressin model class

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        #initialize model parameters
        #requires_grad = True means PyTorch will track the gradients of this
        #specific parameters for use with torch.autograd and gradient descent
        self.weights = nn.Parameter(torch.randn(1, requires_grad = True,dtype = torch.float))
        
        self.bias = nn.Parameter(torch.randn(1,requires_grad = True, dtype = torch.float))
        
        #forward method to define the computation in the model
    def forward(self, x:torch.Tensor) -> torch.Tensor:# x is the input data
        return self.weights * x + self.bias # this is the linear regression formula


In [15]:
#checking content of pytorch model

# checking model parameters using .parameters()

torch.manual_seed(42)
#CREATING instance of the model
model_0 = LinearRegressionModel()

#check out the parameters
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [16]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [14]:
## making prediction using torch.inference_mode()

with torch.inference_mode():
    y_preds = model_0(X_test)
y_preds

NotImplementedError: Module [LinearRegressionModel] is missing the required "forward" function